// D&D 5e spell data — Player's Handbook list.
// Row: [name, level, school, one-line blurb, classes]
// Class codes: B bard · C cleric · D druid · P paladin · R ranger · S sorcerer · K warlock · W wizard
// Level 0 = cantrip.
(function () {
  var S = [
    // ------------------------------------------------------------- cantrips
    ["Acid Splash",0,"Conjuration","Hurl a bubble of acid at one or two creatures; Dex save or 1d6 acid.","S,W"],
    ["Blade Ward",0,"Abjuration","Resistance to bludgeoning, piercing and slashing until end of your next turn.","B,S,K,W"],
    ["Chill Touch",0,"Necromancy","Spectral hand deals 1d8 necrotic and blocks the target's healing for a turn.","S,K,W"],
    ["Dancing Lights",0,"Evocation","Four hovering lights you can move with a bonus action.","B,S,W"],
    ["Druidcraft",0,"Transmutation","Small nature tricks: predict weather, bloom a flower, snuff a flame.","D"],
    ["Eldritch Blast",0,"Evocation","A beam of force, 1d10 damage; more beams as you gain levels.","K"],
    ["Fire Bolt",0,"Evocation","A mote of fire, 1d10 damage on a hit; ignites unattended objects.","S,W"],
    ["Guidance",0,"Divination","Touched creature adds 1d4 to one ability check within the minute.","C"],
    ["Light",0,"Evocation","An object sheds bright light 20 feet, dim 20 beyond.","B,C,S,W"],
    ["Mage Hand",0,"Conjuration","A spectral hand that can carry, fetch and manipulate up to 10 pounds.","B,S,K,W"],
    ["Mending",0,"Transmutation","Repair a single break or tear in an object over one minute.","B,C,D,S,W"],
    ["Message",0,"Transmutation","Whisper a message to one creature within 120 feet; it can reply.","B,S,W"],
    ["Minor Illusion",0,"Illusion","Create a sound or an object-sized image for a minute.","B,S,K,W"],
    ["Poison Spray",0,"Conjuration","A puff of noxious gas; Con save or 1d12 poison.","D,S,K,W"],
    ["Prestidigitation",0,"Transmutation","Minor magical tricks: sparks, tidying, chilling, trinkets.","B,S,K,W"],
    ["Produce Flame",0,"Conjuration","A flame in your hand for light, or thrown for 1d8 fire.","D"],
    ["Ray of Frost",0,"Evocation","1d8 cold and the target's speed drops 10 feet until your next turn.","S,W"],
    ["Resistance",0,"Abjuration","Touched creature adds 1d4 to one saving throw within the minute.","C,D"],
    ["Sacred Flame",0,"Evocation","Radiant flame ignoring cover; Dex save or 1d8 radiant.","C"],
    ["Shillelagh",0,"Transmutation","Your club or quarterstaff deals 1d8 and uses your spellcasting ability.","D"],
    ["Shocking Grasp",0,"Evocation","1d8 lightning and the target cannot take reactions until its next turn.","S,W"],
    ["Spare the Dying",0,"Necromancy","Stabilise a creature at 0 hit points.","C"],
    ["Thaumaturgy",0,"Transmutation","Minor wonders: booming voice, tremors, flames changing colour.","C"],
    ["Thorn Whip",0,"Transmutation","1d6 piercing and pull a Large or smaller creature 10 feet toward you.","D"],
    ["True Strike",0,"Divination","Advantage on your first attack against the target next turn.","B,S,K,W"],
    ["Vicious Mockery",0,"Enchantment","Insult a creature: 1d4 psychic and disadvantage on its next attack.","B"],

    // ---------------------------------------------------------------- 1st
    ["Alarm",1,"Abjuration","Ward an area; you get a mental or audible alert when it is entered.","R,W"],
    ["Animal Friendship",1,"Enchantment","Convince a beast you mean no harm; Wis save negates.","B,D,R"],
    ["Armor of Agathys",1,"Abjuration","5 temporary hit points; attackers in melee take 5 cold.","K"],
    ["Arms of Hadar",1,"Conjuration","Tendrils burst out: 2d6 necrotic in 10 feet, no reactions on a failed save.","K"],
    ["Bane",1,"Enchantment","Up to three creatures subtract 1d4 from attacks and saves.","B,C"],
    ["Bless",1,"Enchantment","Up to three creatures add 1d4 to attack rolls and saving throws.","C,P"],
    ["Burning Hands",1,"Evocation","A 15-foot cone of flame; Dex save or 3d6 fire.","S,W"],
    ["Charm Person",1,"Enchantment","A humanoid is charmed toward you for an hour; Wis save negates.","B,D,S,K,W"],
    ["Chromatic Orb",1,"Evocation","Hurl a 3d8 orb of acid, cold, fire, lightning, poison or thunder.","S,W"],
    ["Color Spray",1,"Illusion","A dazzling spray blinds creatures totalling 6d10 hit points.","S,W"],
    ["Command",1,"Enchantment","One-word order a creature must obey on its next turn; Wis save negates.","C,P"],
    ["Compelled Duel",1,"Enchantment","A creature is drawn to fight you and struggles to move away.","P"],
    ["Comprehend Languages",1,"Divination","Understand any spoken or written language for an hour.","B,S,K,W"],
    ["Create or Destroy Water",1,"Transmutation","Make or destroy ten gallons of water, or call a brief rain.","C,D"],
    ["Cure Wounds",1,"Evocation","Touch to restore 1d8 + spellcasting modifier hit points.","B,C,D,P,R"],
    ["Detect Evil and Good",1,"Divination","Sense aberrations, celestials, fiends, fey, elementals and undead nearby.","C,P"],
    ["Detect Magic",1,"Divination","Sense magic within 30 feet and see auras of magical school.","B,C,D,P,R,S,W"],
    ["Detect Poison and Disease",1,"Divination","Sense poisons, poisonous creatures and disease within 30 feet.","C,D,P,R"],
    ["Disguise Self",1,"Illusion","Change your appearance, including clothing, for an hour.","B,S,W"],
    ["Dissonant Whispers",1,"Enchantment","A discordant melody: 3d6 psychic and the target flees on a failed save.","B"],
    ["Divine Favor",1,"Evocation","Your weapon attacks deal an extra 1d4 radiant for a minute.","P"],
    ["Ensnaring Strike",1,"Conjuration","Your next hit sprouts vines that restrain the target.","R"],
    ["Entangle",1,"Conjuration","Grasping weeds restrain creatures in a 20-foot square.","D"],
    ["Expeditious Retreat",1,"Transmutation","Dash as a bonus action every turn for up to ten minutes.","S,K,W"],
    ["Faerie Fire",1,"Evocation","Objects and creatures in a cube are outlined; attacks against them have advantage.","B,D"],
    ["False Life",1,"Necromancy","Gain 1d4 + 4 temporary hit points for an hour.","S,W"],
    ["Feather Fall",1,"Transmutation","Up to five falling creatures descend gently for a minute.","B,S,W"],
    ["Find Familiar",1,"Conjuration","Bind a spirit in animal form as your servant and scout.","W"],
    ["Fog Cloud",1,"Conjuration","A 20-foot sphere of fog that heavily obscures.","D,R,S,W"],
    ["Goodberry",1,"Transmutation","Ten berries, each restoring 1 hit point and a day's nourishment.","D,R"],
    ["Grease",1,"Conjuration","A slick 10-foot square; Dex save or fall prone.","W"],
    ["Guiding Bolt",1,"Evocation","4d6 radiant, and the next attack against the target has advantage.","C"],
    ["Hail of Thorns",1,"Conjuration","Your ranged hit bursts into thorns, 1d10 piercing around the target.","R"],
    ["Healing Word",1,"Evocation","Bonus-action healing at range: 1d4 + spellcasting modifier.","B,C,D"],
    ["Hellish Rebuke",1,"Evocation","Reaction: the creature that hurt you takes 2d10 fire.","K"],
    ["Heroism",1,"Enchantment","A creature is immune to fear and gains temporary hit points each turn.","B,P"],
    ["Hex",1,"Enchantment","Extra 1d6 necrotic on your hits; the target has disadvantage on one ability.","K"],
    ["Hunter's Mark",1,"Divination","Mark a quarry: extra 1d6 on your hits and advantage to track it.","R"],
    ["Identify",1,"Divination","Learn an item's properties and any spells affecting a creature.","B,W"],
    ["Illusory Script",1,"Illusion","Writing legible only to those you choose; others see something else.","B,K,W"],
    ["Inflict Wounds",1,"Necromancy","A melee spell attack for 3d10 necrotic.","C"],
    ["Jump",1,"Transmutation","Triple a creature's jump distance for a minute.","D,R,S,W"],
    ["Longstrider",1,"Transmutation","Increase a creature's speed by 10 feet for an hour.","B,D,R,W"],
    ["Mage Armor",1,"Abjuration","An unarmoured creature's AC becomes 13 + Dex for eight hours.","S,W"],
    ["Magic Missile",1,"Evocation","Three darts of force, 1d4+1 each, dividing between targets as you like.","S,W"],
    ["Protection from Evil and Good",1,"Abjuration","Certain creature types cannot charm, frighten or possess the target.","C,P,W"],
    ["Purify Food and Drink",1,"Transmutation","Remove poison and disease from food and drink in a 5-foot sphere.","C,D,P"],
    ["Ray of Sickness",1,"Necromancy","2d8 poison and the target may be poisoned until your next turn.","S,W"],
    ["Sanctuary",1,"Abjuration","Attackers must pass a Wis save to target the warded creature.","C"],
    ["Searing Smite",1,"Evocation","Your next hit adds 1d6 fire and sets the target alight.","P"],
    ["Shield",1,"Abjuration","Reaction: +5 AC and immunity to magic missile until your next turn.","S,W"],
    ["Shield of Faith",1,"Abjuration","A shimmering field gives a creature +2 AC for ten minutes.","C,P"],
    ["Silent Image",1,"Illusion","A soundless 15-foot image you can move with your action.","B,S,W"],
    ["Sleep",1,"Enchantment","5d8 hit points of creatures fall unconscious, weakest first.","B,S,W"],
    ["Speak with Animals",1,"Divination","Converse with beasts for ten minutes.","B,D,R"],
    ["Tasha's Hideous Laughter",1,"Enchantment","A creature falls prone with laughter, incapacitated; Wis save each round.","B,W"],
    ["Tenser's Floating Disk",1,"Conjuration","A disk of force that follows you carrying 500 pounds.","W"],
    ["Thunderous Smite",1,"Evocation","Your next hit adds 2d6 thunder and may knock the target prone.","P"],
    ["Thunderwave",1,"Evocation","A 15-foot cube of thunder: 2d8 and pushed 10 feet.","B,D,S,W"],
    ["Unseen Servant",1,"Conjuration","An invisible force that performs simple tasks for an hour.","B,K,W"],
    ["Witch Bolt",1,"Evocation","1d12 lightning, then 1d12 each turn you sustain the arc.","S,K,W"],
    ["Wrathful Smite",1,"Evocation","Your next hit adds 1d6 psychic and may frighten the target.","P"],

    // ---------------------------------------------------------------- 2nd
    ["Aid",2,"Abjuration","Three creatures gain 5 maximum and current hit points for eight hours.","C,P"],
    ["Alter Self",2,"Transmutation","Adapt to water, grow natural weapons, or change your appearance.","S,W"],
    ["Animal Messenger",2,"Enchantment","Send a small beast to carry a message up to 50 miles.","B,D,R"],
    ["Arcane Lock",2,"Abjuration","A door or chest is locked to all but those you name.","W"],
    ["Augury",2,"Divination","Learn whether a course of action in the next half hour is good or ill.","C"],
    ["Barkskin",2,"Transmutation","A creature's AC cannot be lower than 16 for an hour.","D,R"],
    ["Beast Sense",2,"Divination","See and hear through a willing beast's senses.","D,R"],
    ["Blindness/Deafness",2,"Necromancy","Blind or deafen a creature for a minute; Con save each round.","B,C,S,W"],
    ["Blur",2,"Illusion","Your form wavers; attackers have disadvantage against you.","S,W"],
    ["Branding Smite",2,"Evocation","Your next hit adds 2d6 radiant and reveals invisible targets.","P"],
    ["Calm Emotions",2,"Enchantment","Suppress charm and fear, or make hostile creatures indifferent.","B,C"],
    ["Cloud of Daggers",2,"Conjuration","Spinning blades fill a 5-foot cube, 4d4 slashing to anyone inside.","B,S,K,W"],
    ["Continual Flame",2,"Evocation","A heatless flame burns on an object until dispelled.","C,W"],
    ["Cordon of Arrows",2,"Transmutation","Four planted arrows fire at creatures entering the area.","R"],
    ["Crown of Madness",2,"Enchantment","A charmed creature must attack a target of your choice each turn.","B,S,K,W"],
    ["Darkness",2,"Evocation","A 15-foot sphere of magical darkness that even darkvision cannot pierce.","S,K,W"],
    ["Darkvision",2,"Transmutation","Give a creature darkvision to 60 feet for eight hours.","D,R,S,W"],
    ["Detect Thoughts",2,"Divination","Read surface thoughts, or probe deeper against a Wis save.","B,S,W"],
    ["Enhance Ability",2,"Transmutation","Advantage on one ability's checks, with an extra benefit per ability.","B,C,D,S"],
    ["Enlarge/Reduce",2,"Transmutation","Double or halve a creature's size, altering damage and Strength checks.","S,W"],
    ["Enthrall",2,"Enchantment","Distracting words: creatures have disadvantage on Perception to notice others.","B,K"],
    ["Find Steed",2,"Conjuration","Summon a spirit steed bonded to you, intelligent and loyal.","P"],
    ["Find Traps",2,"Divination","Sense whether a trap is present within range.","C,D,R"],
    ["Flame Blade",2,"Evocation","A scimitar of fire dealing 3d6 on a melee spell attack.","D"],
    ["Flaming Sphere",2,"Conjuration","A rolling 5-foot ball of fire, 2d6 to those it touches.","D,W"],
    ["Gentle Repose",2,"Necromancy","A corpse does not decay and cannot be raised as undead.","C,W"],
    ["Gust of Wind",2,"Evocation","A 60-foot line of strong wind that pushes creatures 15 feet.","D,S,W"],
    ["Heat Metal",2,"Transmutation","Metal glows red hot: 2d8 fire, and the holder may drop it.","B,D"],
    ["Hold Person",2,"Enchantment","Paralyse a humanoid; Wis save at the end of each of its turns.","B,C,D,S,K,W"],
    ["Invisibility",2,"Illusion","A creature is invisible for an hour, until it attacks or casts.","B,S,K,W"],
    ["Knock",2,"Transmutation","Unlock a door, chest or bindings with a loud knock.","S,W"],
    ["Lesser Restoration",2,"Abjuration","End one disease or the blinded, deafened, paralysed or poisoned condition.","B,C,D,P,R"],
    ["Levitate",2,"Transmutation","Raise a creature or object up to 20 feet and hold it there.","S,W"],
    ["Locate Animals or Plants",2,"Divination","Sense the nearest kind of beast or plant within five miles.","B,D,R"],
    ["Locate Object",2,"Divination","Sense the direction of a familiar object within 1,000 feet.","B,C,D,P,R,W"],
    ["Magic Mouth",2,"Illusion","An object speaks a message you set when a trigger occurs.","B,W"],
    ["Magic Weapon",2,"Transmutation","A weapon becomes magical with +1 to attack and damage.","P,W"],
    ["Mirror Image",2,"Illusion","Three duplicates confuse attackers, absorbing hits on a roll.","S,K,W"],
    ["Misty Step",2,"Conjuration","Bonus action: teleport 30 feet to a space you can see.","S,K,W"],
    ["Moonbeam",2,"Evocation","A 5-foot beam of pale light, 2d10 radiant, worse for shapechangers.","D"],
    ["Pass without Trace",2,"Abjuration","Your party leaves no tracks and gains +10 to Stealth.","D,R"],
    ["Phantasmal Force",2,"Illusion","An illusion only the target perceives, dealing 1d6 psychic if it believes.","B,S,W"],
    ["Prayer of Healing",2,"Evocation","Up to six creatures regain 2d8 + modifier over ten minutes.","C"],
    ["Protection from Poison",2,"Abjuration","Neutralise one poison and grant advantage against poison for an hour.","C,D,P,R"],
    ["Ray of Enfeeblement",2,"Necromancy","The target deals half damage with Strength-based weapon attacks.","K,W"],
    ["Rope Trick",2,"Transmutation","A rope opens into an extradimensional space holding eight creatures.","W"],
    ["Scorching Ray",2,"Evocation","Three rays of fire, 2d6 each, aimed as you choose.","S,W"],
    ["See Invisibility",2,"Divination","See invisible creatures and into the Ethereal Plane for an hour.","B,S,W"],
    ["Shatter",2,"Evocation","A ringing burst: 3d8 thunder in a 10-foot sphere.","B,S,K,W"],
    ["Silence",2,"Illusion","No sound in a 20-foot sphere; verbal spells cannot be cast.","B,C,R"],
    ["Spider Climb",2,"Transmutation","Walk on walls and ceilings with hands free for an hour.","S,K,W"],
    ["Spike Growth",2,"Transmutation","Ground sprouts spikes: 2d4 piercing per 5 feet of movement.","D,R"],
    ["Spiritual Weapon",2,"Evocation","A floating spectral weapon striking for 1d8 + modifier force.","C"],
    ["Suggestion",2,"Enchantment","A reasonable-sounding course of action a creature pursues for eight hours.","B,S,K,W"],
    ["Warding Bond",2,"Abjuration","A bonded creature gains +1 AC and resistance; you share its damage.","C"],
    ["Web",2,"Conjuration","A 20-foot cube of sticky webbing that restrains and burns.","S,W"],
    ["Zone of Truth",2,"Enchantment","Creatures in a 15-foot sphere cannot speak deliberate lies.","B,C,P"],

    // ---------------------------------------------------------------- 3rd
    ["Animate Dead",3,"Necromancy","Raise a corpse as a skeleton or zombie under your command.","C,W"],
    ["Aura of Vitality",3,"Evocation","Heal a creature in a 30-foot aura 2d6 as a bonus action each turn.","P"],
    ["Beacon of Hope",3,"Abjuration","Advantage on death saves and Wis saves; healing rolls maximum.","C"],
    ["Bestow Curse",3,"Necromancy","Curse a creature with disadvantage, lost turns or extra necrotic damage.","B,C,W"],
    ["Blinding Smite",3,"Evocation","Your next hit adds 3d8 radiant and may blind the target.","P"],
    ["Blink",3,"Transmutation","Each turn, roll to vanish to the Ethereal Plane and return.","S,W"],
    ["Call Lightning",3,"Conjuration","A storm cloud drops bolts for 3d10 lightning each turn.","D"],
    ["Clairvoyance",3,"Divination","Create an invisible sensor to see or hear a distant place.","B,C,S,W"],
    ["Conjure Animals",3,"Conjuration","Summon fey spirits in beast form to fight for you.","D,R"],
    ["Conjure Barrage",3,"Conjuration","A 60-foot cone of duplicated weapons or ammunition, 3d8.","R"],
    ["Counterspell",3,"Abjuration","Reaction: interrupt a creature's spell as it casts.","S,K,W"],
    ["Create Food and Water",3,"Conjuration","Food for fifteen humanoids and thirty gallons of water.","C,P"],
    ["Crusader's Mantle",3,"Evocation","Allies in a 30-foot aura deal an extra 1d4 radiant.","P"],
    ["Daylight",3,"Evocation","A 60-foot sphere of daylight that dispels lesser darkness.","C,D,P,R,S"],
    ["Dispel Magic",3,"Abjuration","End spells of 3rd level or lower on a target; higher with a check.","B,C,D,P,S,K,W"],
    ["Elemental Weapon",3,"Transmutation","A weapon gains +1 and an extra 1d4 elemental damage.","P"],
    ["Fear",3,"Illusion","Creatures in a 30-foot cone drop what they hold and flee.","B,S,K,W"],
    ["Feign Death",3,"Necromancy","A willing creature appears dead and is blinded and incapacitated.","B,C,D,W"],
    ["Fireball",3,"Evocation","A 20-foot-radius blast for 8d6 fire; Dex save for half.","S,W"],
    ["Fly",3,"Transmutation","A creature gains a flying speed of 60 feet for ten minutes.","S,K,W"],
    ["Gaseous Form",3,"Transmutation","A creature becomes a misty cloud that can pass through cracks.","S,K,W"],
    ["Glyph of Warding",3,"Abjuration","Inscribe a trap that explodes or casts a stored spell.","B,C,W"],
    ["Haste",3,"Transmutation","Double speed, +2 AC, advantage on Dex saves and an extra action.","S,W"],
    ["Hunger of Hadar",3,"Conjuration","A void of cold and clutching tendrils blinds and gnaws.","K"],
    ["Hypnotic Pattern",3,"Illusion","A twisting pattern charms and incapacitates creatures in a cube.","B,S,K,W"],
    ["Lightning Arrow",3,"Transmutation","Your ranged hit becomes lightning, 4d8, arcing to nearby creatures.","R"],
    ["Lightning Bolt",3,"Evocation","A 100-foot line of lightning for 8d6.","S,W"],
    ["Magic Circle",3,"Abjuration","A cylinder that keeps named creature types out — or in.","C,P,K,W"],
    ["Major Image",3,"Illusion","A 20-foot illusion with sound, smell and temperature.","B,S,K,W"],
    ["Mass Healing Word",3,"Evocation","Up to six creatures regain 1d4 + modifier as a bonus action.","C"],
    ["Meld into Stone",3,"Transmutation","Step into stone and remain hidden inside it for eight hours.","C,D"],
    ["Nondetection",3,"Abjuration","Hide a creature or object from divination for eight hours.","B,R,W"],
    ["Phantom Steed",3,"Illusion","A quasi-real horse with 100-foot speed for an hour.","W"],
    ["Plant Growth",3,"Transmutation","Overgrow terrain to slow movement, or enrich a half mile of crops.","B,D,R"],
    ["Protection from Energy",3,"Abjuration","Resistance to acid, cold, fire, lightning or thunder for an hour.","C,D,R,S,W"],
    ["Remove Curse",3,"Abjuration","End all curses on a creature or unbind a cursed item.","C,P,K,W"],
    ["Revivify",3,"Necromancy","Return a creature dead less than a minute to 1 hit point.","C,P"],
    ["Sending",3,"Evocation","Send a short message to a creature you know, anywhere.","B,C,W"],
    ["Sleet Storm",3,"Conjuration","Freezing rain douses flames, obscures sight and makes ground slick.","D,S,W"],
    ["Slow",3,"Transmutation","Six creatures halve speed, lose reactions and act on alternate turns.","S,W"],
    ["Speak with Dead",3,"Necromancy","Ask a corpse five questions; it answers cryptically.","B,C"],
    ["Speak with Plants",3,"Transmutation","Question and command plants in a 30-foot radius.","B,D,R"],
    ["Spirit Guardians",3,"Conjuration","Spirits swirl in 15 feet: half speed and 3d8 damage.","C"],
    ["Stinking Cloud",3,"Conjuration","A reeking sphere; creatures retch and lose their actions.","B,S,W"],
    ["Tongues",3,"Divination","Understand and be understood in any language for an hour.","B,C,S,K,W"],
    ["Vampiric Touch",3,"Necromancy","3d6 necrotic and you regain half the damage dealt.","K,W"],
    ["Water Breathing",3,"Transmutation","Ten creatures breathe underwater for 24 hours.","D,R,S,W"],
    ["Water Walk",3,"Transmutation","Ten creatures walk across liquid surfaces for an hour.","C,D,R,S"],
    ["Wind Wall",3,"Evocation","A wall of strong wind that turns arrows and gases aside.","D,R"],

    // ---------------------------------------------------------------- 4th
    ["Arcane Eye",4,"Divination","An invisible floating eye you see through and steer.","W"],
    ["Aura of Life",4,"Abjuration","Allies near you resist necrotic damage and rise from 0 hit points.","P"],
    ["Aura of Purity",4,"Abjuration","Allies near you resist poison and shrug off many conditions.","P"],
    ["Banishment",4,"Abjuration","Send a creature to a harmless demiplane for a minute.","C,P,S,K,W"],
    ["Blight",4,"Necromancy","Drain a creature's vitality for 8d8 necrotic; plants suffer worst.","D,S,K,W"],
    ["Compulsion",4,"Enchantment","Force creatures to move in a direction of your choosing.","B"],
    ["Confusion",4,"Enchantment","Creatures in a sphere wander, babble and attack at random.","B,D,S,W"],
    ["Conjure Minor Elementals",4,"Conjuration","Summon elemental spirits to fight at your command.","D,W"],
    ["Conjure Woodland Beings",4,"Conjuration","Summon fey creatures to serve you for an hour.","D,R"],
    ["Control Water",4,"Transmutation","Raise a flood, part a sea, redirect a current or whirlpool.","C,D,W"],
    ["Death Ward",4,"Abjuration","The first blow that would kill the target drops it to 1 instead.","C,P"],
    ["Dimension Door",4,"Conjuration","Teleport yourself and one other up to 500 feet.","B,S,K,W"],
    ["Divination",4,"Divination","One short question about an event within a week, answered truthfully.","C"],
    ["Dominate Beast",4,"Enchantment","Charm a beast and command it, seeing through its eyes.","D,S"],
    ["Fabricate",4,"Transmutation","Turn raw material into a finished object of the same volume.","W"],
    ["Fire Shield",4,"Evocation","Resistance to cold or fire, and attackers take 2d8 in return.","W"],
    ["Freedom of Movement",4,"Abjuration","Ignore difficult terrain, and escape restraints with 5 feet of movement.","B,C,D,R"],
    ["Giant Insect",4,"Transmutation","Enlarge insects into obedient giant versions for ten minutes.","D"],
    ["Grasping Vine",4,"Conjuration","A vine lashes out and pulls a creature 20 feet toward it.","D,R"],
    ["Greater Invisibility",4,"Illusion","A creature is invisible for a minute even while attacking.","B,S,W"],
    ["Guardian of Faith",4,"Conjuration","A spectral guardian deals 20 radiant to enemies who come near.","C"],
    ["Hallucinatory Terrain",4,"Illusion","Disguise natural terrain across a 150-foot cube for a day.","B,D,K,W"],
    ["Ice Storm",4,"Evocation","Hail batters a 20-foot cylinder: 2d8 bludgeoning and 4d6 cold.","D,S,W"],
    ["Locate Creature",4,"Divination","Sense the direction of a known creature within 1,000 feet.","B,C,D,P,R,W"],
    ["Phantasmal Killer",4,"Illusion","A creature's worst fear made visible: frightened and 4d10 psychic a turn.","W"],
    ["Polymorph",4,"Transmutation","Turn a creature into a beast of equal or lower challenge.","B,D,S,W"],
    ["Private Sanctum",4,"Abjuration","Ward an area against sight, sound, divination and teleportation.","W"],
    ["Staggering Smite",4,"Evocation","Your next hit adds 4d6 psychic and staggers the target's turn.","P"],
    ["Stone Shape",4,"Transmutation","Reshape a 5-foot block of stone into any rough form.","C,D,W"],
    ["Stoneskin",4,"Abjuration","Resistance to nonmagical bludgeoning, piercing and slashing.","D,R,S,W"],
    ["Wall of Fire",4,"Evocation","A 60-foot wall of flame, 5d8 fire to those who pass or stand near.","D,S,W"],

    // ---------------------------------------------------------------- 5th
    ["Animate Objects",5,"Transmutation","Up to ten objects rise and fight at your command.","B,S,W"],
    ["Antilife Shell",5,"Abjuration","A barrier living creatures cannot cross while it holds.","D"],
    ["Awaken",5,"Transmutation","Give a beast or plant human intellect and speech; it becomes charmed.","B,D"],
    ["Banishing Smite",5,"Abjuration","Your next hit adds 5d10 force and may banish a weakened target.","P"],
    ["Bigby's Hand",5,"Evocation","A huge spectral hand that punches, grasps, shoves or shields.","W"],
    ["Circle of Power",5,"Abjuration","Allies near you gain advantage against magic and halve its damage.","P"],
    ["Cloudkill",5,"Conjuration","A moving fog of poison, 5d8, that sinks and obscures.","S,W"],
    ["Commune",5,"Divination","Three yes-or-no questions answered by your deity or its servants.","C"],
    ["Commune with Nature",5,"Divination","Learn the terrain, water, inhabitants and dangers within three miles.","D,R"],
    ["Cone of Cold",5,"Evocation","A 60-foot cone of freezing air for 8d8 cold.","S,W"],
    ["Conjure Elemental",5,"Conjuration","Summon an elemental bound to your command while you concentrate.","D,W"],
    ["Conjure Volley",5,"Conjuration","A rain of ammunition over a 40-foot cylinder, 8d8.","R"],
    ["Contact Other Plane",5,"Divination","Question an alien intellect — and risk your own mind.","K,W"],
    ["Contagion",5,"Necromancy","Inflict a debilitating disease on a creature you touch.","C,D"],
    ["Creation",5,"Illusion","Pull matter from the Shadowfell to make an object that fades.","S,W"],
    ["Destructive Wave",5,"Evocation","Thunder splits the ground: 5d6 thunder plus 5d6 radiant or necrotic.","P"],
    ["Dispel Evil and Good",5,"Abjuration","Fey and fiends have disadvantage against you; break or banish them.","C,P"],
    ["Dominate Person",5,"Enchantment","Charm a humanoid and issue commands it must obey.","B,S,W"],
    ["Dream",5,"Illusion","Shape a sleeping creature's dreams, with a message or a nightmare.","B,K,W"],
    ["Flame Strike",5,"Evocation","A column of divine fire: 4d6 fire and 4d6 radiant.","C"],
    ["Geas",5,"Enchantment","Lay a command a creature must follow or suffer 5d10 psychic.","B,C,D,P,W"],
    ["Greater Restoration",5,"Abjuration","End a charm, petrification, curse, exhaustion or reduction.","B,C,D"],
    ["Hallow",5,"Evocation","Sanctify an area against certain creatures and add a lasting effect.","C"],
    ["Hold Monster",5,"Enchantment","Paralyse any creature but the undead; Wis save each turn.","B,S,K,W"],
    ["Insect Plague",5,"Conjuration","A biting swarm fills a 20-foot sphere for 4d10 piercing.","C,D,S"],
    ["Legend Lore",5,"Divination","Learn the significant lore of a person, place or object.","B,C,W"],
    ["Mass Cure Wounds",5,"Evocation","Six creatures in a 30-foot sphere regain 3d8 + modifier.","B,C,D"],
    ["Mislead",5,"Illusion","Become invisible while an illusory double acts in your place.","B,W"],
    ["Modify Memory",5,"Enchantment","Reshape a creature's memory of an event in the past day.","B,W"],
    ["Passwall",5,"Transmutation","Open a 20-foot passage through wood, plaster or stone.","W"],
    ["Planar Binding",5,"Abjuration","Bind a summoned celestial, elemental, fey or fiend to serve you.","B,C,D,W"],
    ["Raise Dead",5,"Necromancy","Return a creature dead up to ten days, weakened for a time.","B,C,P"],
    ["Reincarnate",5,"Transmutation","A dead humanoid returns in a new body, memories intact.","D"],
    ["Scrying",5,"Divination","See and hear a creature or place anywhere on the same plane.","B,C,D,K,W"],
    ["Seeming",5,"Illusion","Change the appearance of any number of creatures for eight hours.","B,S,W"],
    ["Swift Quiver",5,"Transmutation","Your quiver never empties and you attack twice as a bonus action.","R"],
    ["Telekinesis",5,"Transmutation","Move creatures or objects with your mind, round after round.","S,W"],
    ["Teleportation Circle",5,"Conjuration","Open a portal to a permanent circle you know the sigils for.","B,S,W"],
    ["Tree Stride",5,"Conjuration","Step into one tree and out of another up to 500 feet away.","D,R"],
    ["Wall of Force",5,"Evocation","An invisible, immovable wall nothing physical can pass.","W"],
    ["Wall of Stone",5,"Evocation","Ten stone panels you can shape into a wall, bridge or ramp.","D,S,W"],

    // ---------------------------------------------------------------- 6th
    ["Arcane Gate",6,"Conjuration","Two linked portals up to 500 feet apart, for ten minutes.","S,K,W"],
    ["Blade Barrier",6,"Evocation","A wall of whirling blades, 6d10 slashing, that also gives cover.","C"],
    ["Chain Lightning",6,"Evocation","10d8 lightning that leaps to three more creatures.","S,W"],
    ["Circle of Death",6,"Necromancy","A 60-foot sphere of negative energy for 8d6 necrotic.","S,K,W"],
    ["Conjure Fey",6,"Conjuration","Summon a fey creature or fey-natured beast to serve you.","D,K"],
    ["Contingency",6,"Evocation","Store a spell that triggers on a circumstance you name.","W"],
    ["Create Undead",6,"Necromancy","Raise up to three ghouls under your command.","C,K,W"],
    ["Disintegrate",6,"Transmutation","10d6 + 40 force; a creature reduced to 0 becomes dust.","S,W"],
    ["Drawmij's Instant Summons",6,"Conjuration","Call a marked object to your hand from any distance.","W"],
    ["Eyebite",6,"Necromancy","Your gaze sickens, panics or puts creatures to sleep each turn.","B,S,K,W"],
    ["Find the Path",6,"Divination","Know the shortest route to a place you have been.","B,C,D"],
    ["Flesh to Stone",6,"Transmutation","Petrify a creature over several failed saving throws.","K,W"],
    ["Forbiddance",6,"Abjuration","Ward a building against teleportation and damage named creature types.","C"],
    ["Globe of Invulnerability",6,"Abjuration","A barrier that blocks spells of 5th level and lower.","S,W"],
    ["Guards and Wards",6,"Abjuration","Fill a stronghold with fog, webs, confusion and locked doors.","B,W"],
    ["Harm",6,"Necromancy","14d6 necrotic and the target's maximum hit points drop.","C"],
    ["Heal",6,"Evocation","Restore 70 hit points and end blindness, deafness and disease.","C,D"],
    ["Heroes' Feast",6,"Conjuration","A feast that cures disease, ends fear and raises maximum hit points.","C,D"],
    ["Magic Jar",6,"Necromancy","Move your soul into a container, then into another body.","W"],
    ["Mass Suggestion",6,"Enchantment","Twelve creatures pursue a suggested course for a full day.","B,S,K,W"],
    ["Move Earth",6,"Transmutation","Reshape terrain across a 40-foot square: dig, raise, level.","D,S,W"],
    ["Otiluke's Freezing Sphere",6,"Evocation","A globe of cold for 10d6, or held and thrown later.","W"],
    ["Otto's Irresistible Dance",6,"Enchantment","A creature dances helplessly, unable to fight well or flee.","B,W"],
    ["Planar Ally",6,"Conjuration","Call a servant of your deity — it will want payment.","C"],
    ["Programmed Illusion",6,"Illusion","An illusion that plays out when a condition you set is met.","B,W"],
    ["Sunbeam",6,"Evocation","A line of brilliant light each turn: 6d8 radiant and blindness.","D,S,W"],
    ["Transport via Plants",6,"Conjuration","A doorway between two large plants anywhere on the same plane.","D"],
    ["True Seeing",6,"Divination","See through illusions, invisibility and shapechanging for an hour.","B,C,S,K,W"],
    ["Wall of Ice",6,"Evocation","A wall of ice that blocks, chills and breaks into shards.","W"],
    ["Wall of Thorns",6,"Conjuration","A wall of spiked brambles, 7d8 piercing to pass through.","D"],
    ["Wind Walk",6,"Transmutation","You and companions become gaseous and fly 300 feet a round.","D"],
    ["Word of Recall",6,"Conjuration","Teleport yourself and five others to a sanctuary you consecrated.","C"],

    // ---------------------------------------------------------------- 7th
    ["Conjure Celestial",7,"Conjuration","Summon a celestial of challenge 4 to aid you.","C"],
    ["Delayed Blast Fireball",7,"Evocation","A bead of fire that grows 1d6 each round until it detonates.","S,W"],
    ["Divine Word",7,"Evocation","A word of creation that deafens, blinds, stuns or slays.","C"],
    ["Etherealness",7,"Transmutation","Step into the Ethereal Plane and move through solid matter.","B,C,S,K,W"],
    ["Finger of Death",7,"Necromancy","7d8 + 30 necrotic; a slain humanoid rises as your zombie.","S,K,W"],
    ["Fire Storm",7,"Evocation","Roaring flame fills ten 10-foot cubes for 7d10 fire.","C,D,S"],
    ["Forcecage",7,"Evocation","An inescapable cage or box of invisible force.","B,K,W"],
    ["Mirage Arcane",7,"Illusion","Make a square mile of terrain look, sound and feel like something else.","B,D,W"],
    ["Mordenkainen's Magnificent Mansion",7,"Conjuration","An extradimensional dwelling with servants and a banquet.","B,W"],
    ["Mordenkainen's Sword",7,"Evocation","A spectral blade you direct each turn for 3d10 force.","B,W"],
    ["Plane Shift",7,"Conjuration","Travel to another plane of existence, or banish one creature there.","C,D,S,K,W"],
    ["Prismatic Spray",7,"Evocation","Eight rays of colour, each a different damage or dire effect.","S,W"],
    ["Project Image",7,"Illusion","An illusory double you see and speak through, up to 500 miles off.","B,W"],
    ["Regenerate",7,"Transmutation","Heal 4d8 + 15 and regrow severed limbs over an hour.","B,C,D"],
    ["Resurrection",7,"Necromancy","Return a creature dead up to a century, whole and rested.","B,C"],
    ["Reverse Gravity",7,"Transmutation","Everything in a 50-foot cylinder falls upward.","D,S,W"],
    ["Sequester",7,"Transmutation","Hide an object or creature from sight and divination, in stasis.","W"],
    ["Simulacrum",7,"Illusion","A duplicate of a creature formed from snow, obedient to you.","W"],
    ["Symbol",7,"Abjuration","A glyph that explodes into death, fear, madness or sleep.","B,C,W"],
    ["Teleport",7,"Conjuration","Move yourself and up to eight others hundreds of miles.","B,S,W"],

    // ---------------------------------------------------------------- 8th
    ["Animal Shapes",8,"Transmutation","Turn willing creatures into beasts of challenge 4 or lower.","D"],
    ["Antimagic Field",8,"Abjuration","A 10-foot sphere in which magic simply does not work.","C,W"],
    ["Antipathy/Sympathy",8,"Enchantment","Make a target repellent or irresistible to a kind of creature.","D,W"],
    ["Clone",8,"Necromancy","Grow a duplicate body that receives the original's soul at death.","W"],
    ["Control Weather",8,"Transmutation","Change precipitation, temperature and wind for five miles.","C,D,W"],
    ["Demiplane",8,"Conjuration","A shadowy door to a 30-foot room you create or revisit.","C,K,W"],
    ["Dominate Monster",8,"Enchantment","Charm any creature and command it for an hour.","B,S,K,W"],
    ["Earthquake",8,"Evocation","The ground ruptures: fissures, collapsing structures, creatures knocked prone.","C,D,S"],
    ["Feeblemind",8,"Enchantment","4d6 psychic and the target's Intelligence and Charisma drop to 1.","B,D,K,W"],
    ["Glibness",8,"Transmutation","Treat any Charisma check as at least 15, and defeat lie detection.","B,K"],
    ["Holy Aura",8,"Abjuration","Allies gain advantage on saves, attackers disadvantage, fiends are blinded.","C"],
    ["Incendiary Cloud",8,"Conjuration","A rolling cloud of smoke and embers, 10d8 fire a turn.","S,W"],
    ["Maze",8,"Conjuration","Banish a creature into a labyrinthine demiplane until it escapes.","W"],
    ["Mind Blank",8,"Abjuration","Immunity to psychic damage, divination and charm for a day.","B,W"],
    ["Power Word Stun",8,"Enchantment","A word that stuns a creature with 150 hit points or fewer.","B,S,K,W"],
    ["Sunburst",8,"Evocation","A flash of sunlight: 12d6 radiant and blindness in 60 feet.","D,S,W"],
    ["Telepathy",8,"Evocation","A mental link with a willing creature anywhere on your plane.","W"],
    ["Tsunami",8,"Conjuration","A 300-foot wall of water that crashes forward for 6d10.","D"],

    // ---------------------------------------------------------------- 9th
    ["Astral Projection",9,"Necromancy","Project yourself and companions into the Astral Plane.","C,K,W"],
    ["Foresight",9,"Divination","A creature cannot be surprised, has advantage on everything, and attackers disadvantage.","B,D,K,W"],
    ["Gate",9,"Conjuration","A portal to another plane, and a summons for a named creature.","C,S,W"],
    ["Imprisonment",9,"Abjuration","Bind a creature in slumber, a gem, a burial or a maze — indefinitely.","K,W"],
    ["Mass Heal",9,"Evocation","Distribute 700 hit points of healing and end several conditions.","C"],
    ["Meteor Swarm",9,"Evocation","Four blazing spheres: 20d6 fire and 20d6 bludgeoning.","S,W"],
    ["Power Word Heal",9,"Evocation","A creature is healed fully and freed from charm, fear and paralysis.","B"],
    ["Power Word Kill",9,"Enchantment","A word that kills a creature with 100 hit points or fewer.","B,S,K,W"],
    ["Prismatic Wall",9,"Abjuration","Seven layers of coloured light, each with its own lethal effect.","W"],
    ["Shapechange",9,"Transmutation","Become any creature of your challenge rating or lower, repeatedly.","D,W"],
    ["Storm of Vengeance",9,"Conjuration","A growing storm of thunder, acid, hail, lightning and wind.","D"],
    ["Time Stop",9,"Transmutation","Take 1d4 + 1 turns while everything else stands still.","S,W"],
    ["True Polymorph",9,"Transmutation","Turn a creature or object into another creature or object, perhaps forever.","B,K,W"],
    ["True Resurrection",9,"Necromancy","Return a creature dead up to two centuries, body restored or replaced.","C,D"],
    ["Weird",9,"Illusion","Each creature in a sphere sees its own worst fear and may die of it.","W"],
    ["Wish",9,"Conjuration","The mightiest spell: duplicate any 8th-level spell, or alter reality.","S,W"]
  ];

  window.SPELLS = S.map(function (r) {
    return { name: r[0], level: r[1], school: r[2], text: r[3], classes: r[4].split(",") };
  });
})();
